export const QUERY_KEY = {
  HEALTH: 'health',
  TEST: 'test',
  KAKAO_LOGIN: 'kakaoLogin',
  MOIM_CATEGORIES: 'moimCategories',
  HOST_APPLY: 'hostApply',
  MOIM_BANNER: 'moimBanner',
  MY_HOST_INFO: 'myHostInfo',
  GUEST_PARTICIPATE: 'guestParticipateMoim',
  GUEST_APPLY: 'guestApplyMoim',
  HOST_MOIM_INFO: 'hostMoimInfo',
  MOIM_DETAIL: 'moimDetail',
  MOIM_DESCRIPTION: 'moimDescription',
  MOIM_HOST: 'moimHost',
  MOIM_NOTICE_LIST: 'moimNoticeList',
} as const;
