export const QUERY_KEY = {
  HEALTH: 'health',
  TEST: 'test',
  KAKAO_LOGIN: 'kakaoLogin',
  MOIM_CATEGORIES: 'moimCategories',
  HOST_APPLY: 'hostApply',
  QUESTION_LIST: 'questionList',
  ANSWER_LIST: 'answerList',
  MOIM_BANNER: 'moimBanner',
  MY_HOST_INFO: 'myHostInfo',
  GUEST_PARTICIPATE: 'guestParticipateMoim',
  GUEST_APPLY: 'guestApplyMoim',
  HOST_MOIM_INFO: 'hostMoimInfo',
  MOIM_DETAIL: 'moimDetail',
  APPLICANT_LIST: 'applicantList',
  MOIM_DESCRIPTION: 'moimDescription',
  MOIM_HOST: 'moimHost',
  MOIM_NOTICE_LIST: 'moimNoticeList',
  MOIM_SUBMIT_REQUEST: 'moimSubmitRequest',
} as const;
